apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    implementation (
        'com.amazonaws.serverless:aws-serverless-java-container-core:2.1.5',
        'jakarta.servlet.jsp:jakarta.servlet.jsp-api:3.1.1',
        'jakarta.el:jakarta.el-api:5.0.1',
        'com.amazonaws:aws-lambda-java-core:1.2.3',
        'com.amazonaws:aws-lambda-java-log4j2:1.6.0',
        'org.crac:crac:1.4.0'
    )
    implementation fileTree(dir: 'jars', include: '*.jar')
}

task buildZip(type: Zip) {
    from compileJava
    from processResources              
    from 'cfml/'
    into('lib') {
        from(configurations.compileClasspath)
    }

}

build.dependsOn buildZip
